version: "3"
services:

  guru-srv:
    image: cloudtesttt/docker-image-guru:jenkins-New-Project-master-52
    ports:
      - "8080:8080"
    networks:
      - frontend
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        

networks:
  frontend:

volumes:
  guru:
